services:
  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: tg_ai_manager_app
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - VALKEY_URL=redis://valkey:6379/0
      - DB_PATH=data.db
    depends_on:
      valkey:
        condition: service_healthy

  valkey:
    image: valkey/valkey:8
    container_name: tg_ai_manager_valkey
    restart: "unless-stopped"
    command: valkey-server --save 60 1 --loglevel warning
    # ports:
    #   - "127.0.0.1:6379:6379"
    volumes:
      - valkey_dev_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  valkey_dev_data:
